# Generated by Django 4.2.7 on 2023-12-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeInfo',
            fields=[
                ('bikeName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customerName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phoneNumber', models.IntegerField()),
                ('bikeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bikeinfo')),
            ],
        ),
        migrations.AddField(
            model_name='bikeinfo',
            name='brandName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand'),
        ),
    ]
